# GEOG 592 — Module 6 Homework
## Indexing Practice

### Python Indexing Refresher

In [64]:
locations = ["Oak", "Pine", "Maple", "Cedar", "Elm"]

#### 1. What value is returned by locations[0]?
Oak

In [65]:
locations[0]

'Oak'

#### 2. What value is returned by locations[4]?
Elm

In [66]:
locations[4]

'Elm'

#### 3. What values are returned by locations[1:4]?
Pine, Maple, Cedar

In [67]:
locations[1:4]

['Pine', 'Maple', 'Cedar']

#### 4. Write an indexing expression that returns "Maple".
locations[2]

In [68]:
locations[2]

'Maple'

In [69]:
points = [[100, 200], [140, 230], [180, 260], [120, 280]]

#### 5. What does points[2] return?
[180, 260]

In [70]:
points[2]

[180, 260]

#### 6. What does points[2][1] return? Explain what each index selects.
260, the first index, [2], selects the list in the second index position and the second index selects the individual value in the first index in the list.

In [71]:
points[2][1]

260

#### 7. Write an expression that returns the x-coordinate of the second point. Assume the coordinates are stored as [x,y].
points[1][0]

In [72]:
points[1][0]

140

### Pandas Indexing Refresher

In [73]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Oak", "Pine", "Maple", "Cedar"],
    "ft": [25, 48, 31, 60],
    "zone": ["A", "B", "A", "B"]
})

#### 8. What type of object is returned by df["ft"]?
Series

In [74]:
print(type(df["ft"]))

<class 'pandas.Series'>

#### 9. Write code to select the name and ft columns together.
df[["name", "ft"]]

In [75]:
df[["name", "ft"]]

    name  ft
0    Oak  25
1   Pine  48
2  Maple  31
3  Cedar  60

#### 10. What row is returned by df.iloc[1]?
The second row:\
name: Pine\
ft: 48\
zone: B

In [76]:
df.iloc[1]

name    Pine
ft        48
zone       B
Name: 1, dtype: object

#### 11. Write code using iloc to select the first three rows.
df.iloc[0:3]

In [77]:
df.iloc[0:3]

    name  ft zone
0    Oak  25    A
1   Pine  48    B
2  Maple  31    A

#### 12. Write code to select rows where ft is greater than 30.
df[df["ft"]>30]

In [78]:
df[df["ft"]>30]

    name  ft zone
1   Pine  48    B
2  Maple  31    A
3  Cedar  60    B

#### 13. What rows are returned by df.iloc[1:3]?
The second & third row:\
name: Pine, Maple\
ft: 48, 31\
zone: B, A

In [79]:
df.iloc[1:3]

    name  ft zone
1   Pine  48    B
2  Maple  31    A

### Moving to NumPy Arrays

In [80]:
import numpy as np
points = np.array([
    [100, 200],
    [140, 230],
    [180, 260],
    [120, 280]
])

#### 14. What does points.shape return, and what do the two numbers mean?
(4,2) --> 4 rows & 2 columns

In [81]:
points.shape

(4, 2)

#### 15. What does points[0] return?
array([100,200])

In [82]:
points[0]

array([100, 200])

#### 16. What does points[0, 1] return?
200

In [83]:
points[0,1]

np.int64(200)

#### 17. What does points[:, 0] return? Explain the colon.
array([100,140,180,120]) --> The colon indicates the selection of all rows

In [84]:
points[:,0]

array([100, 140, 180, 120])

#### 18. What does points[:, 1] return?
array([200,230,260,280])

In [85]:
points[:,1]

array([200, 230, 260, 280])

#### 19. Write NumPy indexing code that returns the second and third rows.
points[1:4]

In [86]:
points[1:4]

array([[140, 230],
       [180, 260],
       [120, 280]])

#### 20. Compare points[2][1] with points[2, 1].
points[2][1] will index within a hierarchical Python list that might contain a list within a list. points[2,1] on the other hand is used for indexing within a NumPy array.

In [87]:
points[2][1]
points[2,1]

np.int64(260)

### Vectorized Operations

In [88]:
shift = np.array([10, 20])

#### 21. Without running the code, determine the result of points + shift.
([[110,220],\
[150,250],\
[190,280],\
[130,300]])

In [89]:
points + shift

array([[110, 220],
       [150, 250],
       [190, 280],
       [130, 300]])

#### 22. Why does this operation not require a Python for loop?
There is essentially an already store methon with NumPy to complete the loop through each set of coordinates within "points". When we store each array with NumPy we can just call on the already stored operation.

### Boolean Masks and Spatial Queries

In [90]:
x = points[:, 0]
y = points[:, 1]

inside = (x >= 110) & (x <= 150) & (y >= 220) & (y <= 290)

#### 23. Write the Boolean values stored in inside[:].
array([False, True, False, True])

In [91]:
inside[:]

array([False,  True, False,  True])

#### 24. What does points[inside] return?
array([140,230],
[120,180])

In [92]:
points[inside]

array([[140, 230],
       [120, 280]])

#### 25. In GIS language, what spatial operation is this Boolean mask approximating?
Vectorization

### np.where() and Classification

In [93]:
elevation = np.array([240,510,430,680])
classes = np.where(elevation >= 500, 1, 0)

#### 26. What values are stored in classes[:]?
array([0,1,0,1])

In [94]:
classes[:]

array([0, 1, 0, 1])

#### 27. In your own words, explain the three arguments in np.where(condition, value_if_true, value_if_false).
The first argument is a condition that designates which values to select (ex. x > 3), the second argument is the value to store if the condition is true and the final argument is the value to store if the condition is not met.

### Distance and Pandas Connection

In [95]:
a = np.array([100, 200])
b = np.array([140, 230])
distance = np.sqrt(((a - b) ** 2).sum())

#### 28. What does a - b return?
array([-40, -30])

In [96]:
a - b

array([-40, -30])

#### 29. Explain why this calculation is an example of vectorized arithmetic.
```python
distance = np.sqrt(((a - b) ** 2).sum())
```
This is an example of vectorized arithmetic b/c rather than writing a loop for this equation to apply to every row, NumPy will perform the operation on the whole array.

In [97]:
ft_array = df["ft"].to_numpy()

#### 30. What type of object is ft_array?
numpy.ndarray

In [98]:
type(ft_array)

numpy.ndarray

#### 31. What happened to the pandas index and column label when the Series was converted to NumPy?
The index and column label will be removed and only the values in the "ft" list will be extracted and stored in "ft_array".

### Big Picture
#### 32. Complete the table by describing what is being selected.
**Python list:** locations[2]\
third value in list\
\
**Nested Python list:** points_list[2][1]\
third list, second value in list\
\
**pandas DataFrame:** df.iloc[2,1]:\
third row, second column\
\
**NumPy array:** point[2,1]\
third point list, second value\
\
**NumPy array:** point[:,0]\
all rows, first column values

#### 33. In one sentence: what is the main indexing idea that stays the same across Python, pandas, and NumPy?
The main indexing idea that remained the same across Python, pandas, and NumPy is the ordering of the index starting w/ 0 and the use of a colon to indicate the selection of all items or certain values based on ordering (ex. 1:3).
#### 34. What becomes easier when data are arranged as a 2-D NumPy array?
Any mathematical operation that needs to be performed across the entire dataset w/ vectorized math operations.